name: Tests

on: push

jobs:
    linux-tests:
        name: Linux-Tests with PHP ${{ matrix.php }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php:
                    - 8.3

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: xdebug
                    ini-values: memory_limit=1G

            -   name: Install Composer dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            -   name: Static Code Analyzer
                run: vendor/bin/phpstan

            -   name: Tests
                run: vendor/bin/phpunit

    windows-tests:
        name: Windows-Tests with PHP ${{ matrix.php-versions }}
        runs-on: windows-2019

        strategy:
            fail-fast: true
            matrix:
                php-versions: ['8.3']

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    ini-values: memory_limit=1G

            -   name: Install Composer dependencies
                run: composer update --no-progress --prefer-dist --optimize-autoloader

            -   name: Static Code Analyzer
                run: vendor/bin/phpstan

            -   name: Tests
                run: vendor/bin/phpunit
